<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mmMobileLearning" nsURI="http://www.example.org/mmMobileLearning"
    nsPrefix="MobileLearning">
  <eClassifiers xsi:type="ecore:EClass" name="MKnowledgeDomain">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mHasConcept" upperBound="-1"
        eType="#//MConcept" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mNameKD" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kDomainToMmodule" upperBound="-1"
        eType="#//MModule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mKdomainToScreen" upperBound="-1"
        eType="#//Screen" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MConcept">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameMConcept" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mSubConcept" upperBound="-1"
        eType="#//MConcept" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mHasReference" upperBound="-1"
        eType="#//MReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mConceptToScreen" upperBound="-1"
        eType="#//Screen" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mReferenceToConcept" eType="#//MConcept"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mNameReference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Screen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="screenToElementInterface"
        upperBound="-1" eType="#//ElementInterface" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="origemElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="screenToMModule" upperBound="-1"
        eType="#//MModule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Text" eSuperTypes="#//ElementInterface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textDisplay" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textInformation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TextType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Image" eSuperTypes="#//ElementInterface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textinformation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameImg" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathImg" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TextType">
    <eLiterals name="TEXTLINE"/>
    <eLiterals name="MULTLINETEXT" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Video" eSuperTypes="#//ElementInterface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textInformation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameVideo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathVideo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolution" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Audio" eSuperTypes="#//ElementInterface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textInformation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameAudio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathAudio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//ElementInterface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="link" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementInterface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subElementInterface" upperBound="-1"
        eType="#//ElementInterface" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="origemElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MModule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameModule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mModuleToMConcept" upperBound="-1"
        eType="#//MConcept" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subModule" upperBound="-1"
        eType="#//MModule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mModuleToScreen" upperBound="-1"
        eType="#//Screen" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
