/**
 *
 * $Id$
 */
package mmMobileLearning.validation;

import mmMobileLearning.ElementInterface;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link mmMobileLearning.ElementInterface}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ElementInterfaceValidator {
	boolean validate();

	boolean validateLabel(String value);
	boolean validateSubElementInterface(EList<ElementInterface> value);
	boolean validateOrigemElement(String value);
}
