/**
 *
 * $Id$
 */
package mmMobileLearning.validation;

import mmMobileLearning.MConcept;

/**
 * A sample validator interface for {@link mmMobileLearning.MReference}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MReferenceValidator {
	boolean validate();

	boolean validateMReferenceToConcept(MConcept value);
	boolean validateMNameReference(String value);
}
