/**
 *
 * $Id$
 */
package mmMobileLearning.validation;


/**
 * A sample validator interface for {@link mmMobileLearning.Video}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VideoValidator {
	boolean validate();

	boolean validateTextInformation(String value);
	boolean validateNameVideo(String value);
	boolean validatePathVideo(String value);
	boolean validateResolution(String value);
	boolean validateTime(int value);
}
