/**
 *
 * $Id$
 */
package reactNative.validation;

import org.eclipse.emf.common.util.EList;

import reactNative.Image;
import reactNative.Text;
import reactNative.View;

/**
 * A sample validator interface for {@link reactNative.FlatList}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FlatListValidator {
	boolean validate();

	boolean validateHasViews(EList<View> value);
	boolean validateFlatListText(EList<Text> value);
	boolean validateFlatlistName(String value);
	boolean validateImage(EList<Image> value);
	boolean validateData(String value);
	boolean validateRenderItem(String value);
	boolean validateKeyExtractor(String value);
}
