/**
 *
 * $Id$
 */
package reactNative.validation;

import org.eclipse.emf.common.util.EList;

import reactNative.Component;

/**
 * A sample validator interface for {@link reactNative.ProjetoRN}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProjetoRNValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateComponents(EList<Component> value);
}
