/**
 *
 * $Id$
 */
package reactNative.validation;

import org.eclipse.emf.common.util.EList;

import reactNative.StyleSheet;
import reactNative.Text;

/**
 * A sample validator interface for {@link reactNative.Text}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TextValidator {
	boolean validate();

	boolean validateContentText(String value);
	boolean validateColor(String value);
	boolean validateFontSize(int value);
	boolean validateTextAlign(String value);
	boolean validateSubText(EList<Text> value);
	boolean validateName(String value);
	boolean validateTextToStylesheet(EList<StyleSheet> value);
}
