/**
 *
 * $Id$
 */
package reactNative.validation;

import org.eclipse.emf.common.util.EList;

import reactNative.Array;
import reactNative.ObjectElement;

/**
 * A sample validator interface for {@link reactNative.Array}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ArrayValidator {
	boolean validate();

	boolean validateValue(String value);
	boolean validateSubArray(EList<Array> value);
	boolean validateArrayToObjects(EList<ObjectElement> value);
}
