/**
 *
 * $Id$
 */
package reactNative.validation;

import org.eclipse.emf.common.util.EList;

import reactNative.Text;
import reactNative.TouchableOpacity;
import reactNative.View;

/**
 * A sample validator interface for {@link reactNative.Component}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComponentValidator {
	boolean validate();

	boolean validateComponentTotext(EList<Text> value);
	boolean validateComponentName(String value);
	boolean validateComponentToView(EList<View> value);
	boolean validateState(boolean value);
	boolean validateComponentToTouchableOpacity(TouchableOpacity value);
}
