/**
 *
 * $Id$
 */
package reactNative.validation;

import org.eclipse.emf.common.util.EList;

import reactNative.Array;

/**
 * A sample validator interface for {@link reactNative.ElementImage}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ElementImageValidator {
	boolean validate();

	boolean validateContentImage(String value);
	boolean validateValueImage(String value);
	boolean validateElementImageToArray(EList<Array> value);
}
