/**
 *
 * $Id$
 */
package reactNative.validation;

import org.eclipse.emf.common.util.EList;
import reactNative.Array;


/**
 * A sample validator interface for {@link reactNative.ElementText}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ElementTextValidator {
	boolean validate();

	boolean validateContentText(String value);
	boolean validateValueText(String value);

	boolean validateElementTextToArray(EList<Array> value);
}
