/**
 *
 * $Id$
 */
package reactNative.validation;

import org.eclipse.emf.common.util.EList;

import reactNative.StyleSheet;

/**
 * A sample validator interface for {@link reactNative.Icon}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IconValidator {
	boolean validate();

	boolean validateStyle(String value);
	boolean validateName(String value);
	boolean validateSize(int value);
	boolean validateColor(String value);
	boolean validateIconToStylesheet(EList<StyleSheet> value);
}
