/**
 *
 * $Id$
 */
package reactNative.validation;

import reactNative.Border;
import reactNative.FlexBox;
import reactNative.Font;
import reactNative.Margin;
import reactNative.Padding;

/**
 * A sample validator interface for {@link reactNative.StyleSheet}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StyleSheetValidator {
	boolean validate();

	boolean validateNameStyle(String value);
	boolean validateHasFlexbox(FlexBox value);
	boolean validateHasFont(Font value);
	boolean validateHasMargin(Margin value);

	boolean validateHasBorder(Border value);

	boolean validateHasPadding(Padding value);
}
