/**
 *
 * $Id$
 */
package reactNative.validation;

import org.eclipse.emf.common.util.EList;

import reactNative.Button;
import reactNative.Icon;
import reactNative.Image;
import reactNative.Text;
import reactNative.View;

/**
 * A sample validator interface for {@link reactNative.TouchableOpacity}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TouchableOpacityValidator {
	boolean validate();

	boolean validateTouchableOpacityToIcon(EList<Icon> value);
	boolean validateTouchableOpacityToImage(EList<Image> value);
	boolean validateTouchableOpacityToText(EList<Text> value);
	boolean validateTouchableOpacityView(EList<View> value);
	boolean validateTouchableOpacityToButton(EList<Button> value);
}
