/**
 *
 * $Id$
 */
package reactNative.validation;

import org.eclipse.emf.common.util.EList;

import reactNative.Button;
import reactNative.FlatList;
import reactNative.Icon;
import reactNative.Image;
import reactNative.SectionList;
import reactNative.StyleSheet;
import reactNative.Text;
import reactNative.TouchableOpacity;
import reactNative.View;

/**
 * A sample validator interface for {@link reactNative.View}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ViewValidator {
	boolean validate();

	boolean validateHasText(EList<Text> value);
	boolean validateViewToflatlists(EList<FlatList> value);
	boolean validateViewType(int value);
	boolean validateViewName(String value);
	boolean validateHasImage(EList<Image> value);
	boolean validateViewToTouchableOpacity(EList<TouchableOpacity> value);
	boolean validateViewToIcon(EList<Icon> value);
	boolean validateViewToButton(EList<Button> value);
	boolean validateSubView(EList<View> value);
	boolean validateViewToStyleSheet(EList<StyleSheet> value);
	boolean validateViewToSectionList(SectionList value);
}
