<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="reactNative" nsURI="http://www.example.org/reactNative" nsPrefix="reactNative">
  <eClassifiers xsi:type="ecore:EClass" name="View">
    <eOperations name="style">
      <eParameters name="style" eType="#//StyleSheet"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasText" upperBound="-1"
        eType="#//Text" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ViewToflatlists" upperBound="-1"
        eType="#//FlatList" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewType" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewName" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasImage" upperBound="-1"
        eType="#//Image" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewToTouchableOpacity"
        upperBound="-1" eType="#//TouchableOpacity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewToIcon" upperBound="-1"
        eType="#//Icon" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewToButton" upperBound="-1"
        eType="#//Button" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subView" upperBound="-1"
        eType="#//View" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ViewToStyleSheet" upperBound="-1"
        eType="#//StyleSheet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewToSectionList" eType="#//SectionList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Text">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentText" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fontSize" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textAlign" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TextToStylesheet" upperBound="-1"
        eType="#//StyleSheet" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlatList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasViews" upperBound="-1"
        eType="#//View" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flatlistName" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="renderItem" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyExtractor" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flatListToArray" upperBound="-1"
        eType="#//Array" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentTotext" upperBound="-1"
        eType="#//Text" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="componentName" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentToView" upperBound="-1"
        eType="#//View" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentToTouchableOpacity"
        eType="#//TouchableOpacity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjetoRN">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Image">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imageTostylesheet" upperBound="-1"
        eType="#//StyleSheet" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TouchableOpacity" eSuperTypes="#//TouchablesGenerics">
    <eStructuralFeatures xsi:type="ecore:EReference" name="touchableOpacityToIcon"
        upperBound="-1" eType="#//Icon" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="touchableOpacityToImage"
        upperBound="-1" eType="#//Image" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="touchableOpacityToText"
        upperBound="-1" eType="#//Text" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="touchableOpacityView" upperBound="-1"
        eType="#//View" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="touchableOpacityToButton"
        upperBound="-1" eType="#//Button" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Icon">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="style" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IconToStylesheet" upperBound="-1"
        eType="#//StyleSheet" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TouchablesGenerics" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onPress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Button" eSuperTypes="#//TouchablesGenerics">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disabled" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StyleSheet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameStyle" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasFlexbox" eType="#//FlexBox"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasFont" eType="#//Font"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasMargin" eType="#//Margin"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasBorder" eType="#//Border"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasPadding" eType="#//Padding"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlexBox">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flex" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IntObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flexDirection" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="justifyContent" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alignItems" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Font">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fontSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fontFamily" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fontWeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SectionList">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sectionListName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sections" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="modulo"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyExtractor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="(item, index) => `${item.id}`"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="renderSectionHeader" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="({ section }) => ( )"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="renderItem" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="({ item }) => ( )"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sectionListToArray" upperBound="-1"
        eType="#//Array" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Margin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="marginTop" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="marginBottom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="margin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Array">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subArray" upperBound="-1"
        eType="#//Array" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arrayToObjects" upperBound="-1"
        eType="#//ObjectElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementText">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementTextToArray" upperBound="-1"
        eType="#//Array" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementImage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentImage" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueImage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementImageToArray" upperBound="-1"
        eType="#//Array" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementText" upperBound="-1"
        eType="#//ElementText" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementImage" upperBound="-1"
        eType="#//ElementImage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subObjects" upperBound="-1"
        eType="#//ObjectElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectToArray" upperBound="-1"
        eType="#//Array" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Border">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="borderBottomRightRadius"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="borderColor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="borderRadius" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="borderWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Padding">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="padding" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paddingHorizontal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paddingVertical" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
